[platformio]
default_envs = rp2040

[env]
framework = arduino
lib_deps =
    nRF24/RF24 @ ^1.4.7
    nRF24/RF24Network @ ^1.0.17
    bblanchon/ArduinoJson @ ^6.21.3
monitor_speed = 115200

[env:rp2040]
platform = raspberrypi
board = pico
build_flags = 
    -D IS_RP2040

[env:esp8266]
platform = espressif8266
board = nodemcuv2
build_flags = 
    -D IS_ESP8266

[env:esp32]
platform = espressif32
board = esp32dev
build_flags = 
    -D IS_ESP32

[env:arduino_nano]
platform = atmelavr
board = nanoatmega328
build_flags = 
    -D IS_ARDUINO
